package com.ggy.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Cal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.calid
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    private String calid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.start_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.end_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.title
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.cal_desc
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    private String calDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.ent_who
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    private String entWho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_base.ent_when
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date entWhen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.calid
     *
     * @return the value of cal_base.calid
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public String getCalid() {
        return calid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.calid
     *
     * @param calid the value for cal_base.calid
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public void setCalid(String calid) {
        this.calid = calid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.start_date
     *
     * @return the value of cal_base.start_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.start_date
     *
     * @param startDate the value for cal_base.start_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.end_date
     *
     * @return the value of cal_base.end_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.end_date
     *
     * @param endDate the value for cal_base.end_date
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.title
     *
     * @return the value of cal_base.title
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.title
     *
     * @param title the value for cal_base.title
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.cal_desc
     *
     * @return the value of cal_base.cal_desc
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public String getCalDesc() {
        return calDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.cal_desc
     *
     * @param calDesc the value for cal_base.cal_desc
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public void setCalDesc(String calDesc) {
        this.calDesc = calDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.ent_who
     *
     * @return the value of cal_base.ent_who
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    
    public String getEntWho() {
        return entWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.ent_who
     *
     * @param entWho the value for cal_base.ent_who
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    public void setEntWho(String entWho) {
        this.entWho = entWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_base.ent_when
     *
     * @return the value of cal_base.ent_when
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getEntWhen() {
        return entWhen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_base.ent_when
     *
     * @param entWhen the value for cal_base.ent_when
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setEntWhen(Date entWhen) {
        this.entWhen = entWhen;
    }

	@Override
	public String toString() {
		return "Cal [calid=" + calid + ", startDate=" + startDate + ", endDate=" + endDate + ", title=" + title
				+ ", calDesc=" + calDesc + ", entWho=" + entWho + ", entWhen=" + entWhen + "]";
	}
    
    
}