package com.ggy.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptid
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    private String dname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptid
     *
     * @return the value of dept.deptid
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptid
     *
     * @param deptid the value for dept.deptid
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    public void setDname(String dname) {
        this.dname = dname;
    }
}