package com.ggy.dao;

import com.ggy.pojo.Cal;

public interface CalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String calid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    int insert(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    int insertSelective(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    Cal selectByPrimaryKey(String calid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 11:06:23 GMT+08:00 2018
     */
    int updateByPrimaryKey(Cal record);
}