package com.ggy.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.ggy.pojo.Cal;

public interface CalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String calid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    int insert(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    int insertSelective(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    Cal selectByPrimaryKey(String calid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Cal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_base
     *
     * @mbggenerated Wed Mar 21 16:56:56 GMT+08:00 2018
     */
    int updateByPrimaryKey(Cal record);

	Integer isExist(String calid);

	List<Date> getCals();

	List<Map<String, String>> getCalByDate(String startDate);
}