package com.ggy.dao;

import java.util.List;
import java.util.Map;

import com.ggy.pojo.Dept;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    Dept selectByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Fri Mar 09 10:15:15 GMT+08:00 2018
     */
    int updateByPrimaryKey(Dept record);
//展示所有部门
	List<Map<String, String>> showDept();
//根据部门名称获取部门id
	int getDeptIdByDname(String dname);
}